// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr7xQPAyZABFJWAgBTm4RS6PEMzK7-BCg',
    appId: '1:218569797510:web:1880055dc6e8f60ef98607',
    messagingSenderId: '218569797510',
    projectId: 'orina-auth',
    authDomain: 'orina-auth.firebaseapp.com',
    storageBucket: 'orina-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxqtd7nqIeQL7nr96Bh6Q1PAhum513c8',
    appId: '1:218569797510:android:96df1011a64eee11f98607',
    messagingSenderId: '218569797510',
    projectId: 'orina-auth',
    storageBucket: 'orina-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7vUI6RnasmrcVfIPGJiQ7-zNsDd6zlFY',
    appId: '1:218569797510:ios:647f6af6525ccaecf98607',
    messagingSenderId: '218569797510',
    projectId: 'orina-auth',
    storageBucket: 'orina-auth.firebasestorage.app',
    iosClientId: '218569797510-s221mr6pumv1nvhsf0eibeinkitl775t.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeInitial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7vUI6RnasmrcVfIPGJiQ7-zNsDd6zlFY',
    appId: '1:218569797510:ios:647f6af6525ccaecf98607',
    messagingSenderId: '218569797510',
    projectId: 'orina-auth',
    storageBucket: 'orina-auth.firebasestorage.app',
    iosClientId: '218569797510-s221mr6pumv1nvhsf0eibeinkitl775t.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeInitial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr7xQPAyZABFJWAgBTm4RS6PEMzK7-BCg',
    appId: '1:218569797510:web:c7a4dbf9c6cf43baf98607',
    messagingSenderId: '218569797510',
    projectId: 'orina-auth',
    authDomain: 'orina-auth.firebaseapp.com',
    storageBucket: 'orina-auth.firebasestorage.app',
  );
}
